services:
  weather-data:
    image: weather-data
    container_name: weather-data
    ports:
      - "8080:80"
    environment:
      WINDY_API_KEY: ${WINDY_API_KEY}
    volumes:
      - db_data:/app/db

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      device: ./db
      o: bind
