services:
  windy-transform:
    image: windy-transform
    container_name: windy-transform
    ports:
      - "8080:80"
    volumes:
      - db_data:/app/db
      - ./logs:/app/logs

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      device: ./db
      o: bind
